library(dplyr)
RollNo = c(1001,1002,1003,1004)
Name = c("Ram1","Ram2","Ram3","Ram4")
Ages = c(10,30,15,14)
Class = c("I","V","VI","VI")
df = data.frame(RollNo,Name,Ages,Class)
print(df)
df_ = mutate(df,log_age=log(Ages))
print(df_)
df2 = data.frame("RollNo" = c(1001,1002,1004,1003,1005),"Dept" = c("Tech","Marketing","Teaching","Data Science","Angular"))
print(df2)
df_leftJoin = left_join(df,df2,by = "RollNo")
print(df_leftJoin)
df_rightJoin = right_join(df,df2,by = "RollNo")
print(df_rightJoin)
df_rightJoin2 = right_join(df2,df,by = "RollNo")
print(df_rightJoin2) # ~ df_leftJoin
df_innerJoin = inner_join(df,df2,by = "RollNo")
print(df_innerJoin)
df_fullJoin = full_join(df,df2,by = "RollNo")
print(df_fullJoin)
df_semiJoin = semi_join(df,df2,by = "RollNo")
print(df_semiJoin)
df_antiJoin = anti_join(df2,df,by = "RollNo")
print(df_antiJoin)
